# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  stream_options:
    ssl:
      allow_self_signed: true
      verify_peer: false
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
